/*
    MKERNEL HEADER FILE FROM MAP OPERATING SYSTEM
    AUTHOR: KAP PETROV
    DESCRIPTION: MKERNEL SOURCE CODE FROM MAP OPERATING SYSTEM (HEADER FILE)
*/

#ifndef KERNEL_H
#define KERNEL_H



#endif